///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Ofsted_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Ofsted_demoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ff0984de-0aec-4132-950f-c60cfc296620")]
    public partial class Ofsted_demoRepository : RepoGenBaseFolder
    {
        static Ofsted_demoRepository instance = new Ofsted_demoRepository();
        Ofsted_demoRepositoryFolders.MainFormAppFolder _mainform;
        Ofsted_demoRepositoryFolders.PwEntryFormAppFolder _pwentryform;
        Ofsted_demoRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        Ofsted_demoRepositoryFolders.KeePassAppFolder _keepass;

        /// <summary>
        /// Gets the singleton class instance representing the Ofsted_demoRepository element repository.
        /// </summary>
        [RepositoryFolder("ff0984de-0aec-4132-950f-c60cfc296620")]
        public static Ofsted_demoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Ofsted_demoRepository() 
            : base("Ofsted_demoRepository", "/", null, 0, false, "ff0984de-0aec-4132-950f-c60cfc296620", ".\\RepositoryImages\\Ofsted_demoRepositoryff0984de.rximgres")
        {
            _mainform = new Ofsted_demoRepositoryFolders.MainFormAppFolder(this);
            _pwentryform = new Ofsted_demoRepositoryFolders.PwEntryFormAppFolder(this);
            _keypromptform = new Ofsted_demoRepositoryFolders.KeyPromptFormAppFolder(this);
            _keepass = new Ofsted_demoRepositoryFolders.KeePassAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ff0984de-0aec-4132-950f-c60cfc296620")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("9894463d-e2dc-43fd-a546-68375c371d63")]
        public virtual Ofsted_demoRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }

        /// <summary>
        /// The PwEntryForm folder.
        /// </summary>
        [RepositoryFolder("e7ca4022-1122-4f12-8ded-e90e93db85b7")]
        public virtual Ofsted_demoRepositoryFolders.PwEntryFormAppFolder PwEntryForm
        {
            get { return _pwentryform; }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("a522effe-3f6a-44de-882a-c96355680527")]
        public virtual Ofsted_demoRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The KeePass folder.
        /// </summary>
        [RepositoryFolder("2c912d6d-dc62-4bb5-8771-4ae751298781")]
        public virtual Ofsted_demoRepositoryFolders.KeePassAppFolder KeePass
        {
            get { return _keepass; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Ofsted_demoRepositoryFolders
    {
        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("9894463d-e2dc-43fd-a546-68375c371d63")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            Ofsted_demoRepositoryFolders.MSplitHorizontalFolder _msplithorizontal;
            RepoItemInfo _addentryInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _saveInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "9894463d-e2dc-43fd-a546-68375c371d63", "")
            {
                _msplithorizontal = new Ofsted_demoRepositoryFolders.MSplitHorizontalFolder(this);
                _addentryInfo = new RepoItemInfo(this, "AddEntry", "?/?/button[@accessiblename='Add Entry']", 30000, null, "4f864c2a-cd12-4901-b3f5-38a6eaa0739d");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "648b21f8-d6bd-46d1-be20-166ee1aac22f");
                _saveInfo = new RepoItemInfo(this, "Save", "?/?/button[@accessiblename='Save']", 30000, null, "4c9c48ca-7052-4ac8-9da0-221ace824ae2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9894463d-e2dc-43fd-a546-68375c371d63")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9894463d-e2dc-43fd-a546-68375c371d63")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddEntry item.
            /// </summary>
            [RepositoryItem("4f864c2a-cd12-4901-b3f5-38a6eaa0739d")]
            public virtual Ranorex.Button AddEntry
            {
                get
                {
                    return _addentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddEntry item info.
            /// </summary>
            [RepositoryItemInfo("4f864c2a-cd12-4901-b3f5-38a6eaa0739d")]
            public virtual RepoItemInfo AddEntryInfo
            {
                get
                {
                    return _addentryInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("648b21f8-d6bd-46d1-be20-166ee1aac22f")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("648b21f8-d6bd-46d1-be20-166ee1aac22f")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The Save item.
            /// </summary>
            [RepositoryItem("4c9c48ca-7052-4ac8-9da0-221ace824ae2")]
            public virtual Ranorex.Button Save
            {
                get
                {
                    return _saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Save item info.
            /// </summary>
            [RepositoryItemInfo("4c9c48ca-7052-4ac8-9da0-221ace824ae2")]
            public virtual RepoItemInfo SaveInfo
            {
                get
                {
                    return _saveInfo;
                }
            }

            /// <summary>
            /// The MSplitHorizontal folder.
            /// </summary>
            [RepositoryFolder("7f633062-8b97-4f3d-a010-990c6dc1d201")]
            public virtual Ofsted_demoRepositoryFolders.MSplitHorizontalFolder MSplitHorizontal
            {
                get { return _msplithorizontal; }
            }
        }

        /// <summary>
        /// The MSplitHorizontalFolder folder.
        /// </summary>
        [RepositoryFolder("7f633062-8b97-4f3d-a010-990c6dc1d201")]
        public partial class MSplitHorizontalFolder : RepoGenBaseFolder
        {
            RepoItemInfo _generalInfo;
            RepoItemInfo _outlineInfo;
            RepoItemInfo _edgewordsInfo;

            /// <summary>
            /// Creates a new MSplitHorizontal  folder.
            /// </summary>
            public MSplitHorizontalFolder(RepoGenBaseFolder parentFolder) :
                    base("MSplitHorizontal", "container[@controlname='m_splitHorizontal']", parentFolder, 30000, null, false, "7f633062-8b97-4f3d-a010-990c6dc1d201", "")
            {
                _generalInfo = new RepoItemInfo(this, "General", ".//tree[@controlname='m_tvGroups']/?/?/treeitem[@accessiblename='Database']/treeitem[@accessiblename='General']", 30000, null, "e53cb11b-fa25-45ec-b8ac-6e9ef4c981f7");
                _outlineInfo = new RepoItemInfo(this, "Outline", ".//tree[@controlname='m_tvGroups']/tree[@accessiblerole='Outline']", 30000, null, "45691fc6-81ec-40f2-bda6-45dcfccc3428");
                _edgewordsInfo = new RepoItemInfo(this, "Edgewords", "?/?/container[@controlname='m_splitVertical']/?/?/table[@controlname='m_lvEntries']/?/?/cell[@text='edgewords']", 30000, null, "eb8e4e7f-75b8-43f8-830b-7db44548237c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7f633062-8b97-4f3d-a010-990c6dc1d201")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7f633062-8b97-4f3d-a010-990c6dc1d201")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The General item.
            /// </summary>
            [RepositoryItem("e53cb11b-fa25-45ec-b8ac-6e9ef4c981f7")]
            public virtual Ranorex.TreeItem General
            {
                get
                {
                    return _generalInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The General item info.
            /// </summary>
            [RepositoryItemInfo("e53cb11b-fa25-45ec-b8ac-6e9ef4c981f7")]
            public virtual RepoItemInfo GeneralInfo
            {
                get
                {
                    return _generalInfo;
                }
            }

            /// <summary>
            /// The Outline item.
            /// </summary>
            [RepositoryItem("45691fc6-81ec-40f2-bda6-45dcfccc3428")]
            public virtual Ranorex.Tree Outline
            {
                get
                {
                    return _outlineInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Outline item info.
            /// </summary>
            [RepositoryItemInfo("45691fc6-81ec-40f2-bda6-45dcfccc3428")]
            public virtual RepoItemInfo OutlineInfo
            {
                get
                {
                    return _outlineInfo;
                }
            }

            /// <summary>
            /// The Edgewords item.
            /// </summary>
            [RepositoryItem("eb8e4e7f-75b8-43f8-830b-7db44548237c")]
            public virtual Ranorex.Cell Edgewords
            {
                get
                {
                    return _edgewordsInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Edgewords item info.
            /// </summary>
            [RepositoryItemInfo("eb8e4e7f-75b8-43f8-830b-7db44548237c")]
            public virtual RepoItemInfo EdgewordsInfo
            {
                get
                {
                    return _edgewordsInfo;
                }
            }
        }

        /// <summary>
        /// The PwEntryFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("e7ca4022-1122-4f12-8ded-e90e93db85b7")]
        public partial class PwEntryFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _usernameInfo;

            /// <summary>
            /// Creates a new PwEntryForm  folder.
            /// </summary>
            public PwEntryFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("PwEntryForm", "/form[@controlname='PwEntryForm']", parentFolder, 30000, null, true, "e7ca4022-1122-4f12-8ded-e90e93db85b7", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/tabpage[@controlname='m_tabEntry']/text[@controlname='m_tbTitle']/text[@accessiblerole='Text']", 30000, null, "f2a33348-7782-4127-ba3a-a93ee51a2db9");
                _usernameInfo = new RepoItemInfo(this, "UserName", "?/?/tabpage[@controlname='m_tabEntry']/?/?/text[@accessiblename='User name:']", 30000, null, "2e67103e-4540-426e-bd9b-ca69ef61fb4c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7ca4022-1122-4f12-8ded-e90e93db85b7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7ca4022-1122-4f12-8ded-e90e93db85b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("f2a33348-7782-4127-ba3a-a93ee51a2db9")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("f2a33348-7782-4127-ba3a-a93ee51a2db9")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("2e67103e-4540-426e-bd9b-ca69ef61fb4c")]
            public virtual Ranorex.Text UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("2e67103e-4540-426e-bd9b-ca69ef61fb4c")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }
        }

        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("a522effe-3f6a-44de-882a-c96355680527")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30000, null, true, "a522effe-3f6a-44de-882a-c96355680527", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "64164024-8c64-4dee-8be5-714691ff22b6");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "943c9828-44a3-4bc1-9b3c-35a541260b24");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a522effe-3f6a-44de-882a-c96355680527")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a522effe-3f6a-44de-882a-c96355680527")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("64164024-8c64-4dee-8be5-714691ff22b6")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("64164024-8c64-4dee-8be5-714691ff22b6")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("943c9828-44a3-4bc1-9b3c-35a541260b24")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("943c9828-44a3-4bc1-9b3c-35a541260b24")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The KeePassAppFolder folder.
        /// </summary>
        [RepositoryFolder("2c912d6d-dc62-4bb5-8771-4ae751298781")]
        public partial class KeePassAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new KeePass  folder.
            /// </summary>
            public KeePassAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeePass", "/form[@title='KeePass']", parentFolder, 30000, null, true, "2c912d6d-dc62-4bb5-8771-4ae751298781", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/element[@instance='0']/button[@text='&Yes']", 30000, null, "7f753312-e6a4-435b-9293-8afd63582545");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2c912d6d-dc62-4bb5-8771-4ae751298781")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2c912d6d-dc62-4bb5-8771-4ae751298781")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("7f753312-e6a4-435b-9293-8afd63582545")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("7f753312-e6a4-435b-9293-8afd63582545")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
